export const INCREMENT_NUMBER = 'INCREMENT_NUMBER';
export const DECREMENT_NUMBER = 'DECREMENT_NUMBER';

export const LOADING_WEATHER = 'LOADING_WEATHER';
export const GET_DATA_WEATHER = 'GET_DATA_WEATHER';
export const GET_DATA_WEATHER_SUCCESS = 'GET_DATA_WEATHER_SUCCESS';
export const GET_DATA_WEATHER_FAILURE = 'GET_DATA_WEATHER_FAILURE';